#!/usr/bin/env ruby

$:.unshift(File.expand_path("..", __FILE__))
require "completion"

class CodeCompletion < Completion
  private

  def collection
    `ls ~/Code/`.split
  end
end

puts CodeCompletion.new(ENV["COMP_LINE"]).matches
exit 0
