#!/usr/bin/env ruby

$:.unshift(File.expand_path("..", __FILE__))
require "completion"

class SitesCompletion < Completion
  private

  def collection
    `ls ~/Sites/`.split
  end
end

puts SitesCompletion.new(ENV["COMP_LINE"]).matches
exit 0
