#!/usr/bin/env bash

# Colors
e=`printf "\033"`
end="$e[0m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
blue="$e[1;34m"
magenta="$e[1;35m"
darkcyan="$e[1;36m"

# Paths
export PATH="/usr/local/bin:$PATH"
export NODE_PATH="/usr/local/lib/node_modules"

# Prompt
_parse_git_branch() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}") "
}
export PS1="\[${green}\]\w\[${darkcyan}\] \$(_parse_git_branch)\[${green}\]\$\[${end}\] "

# Miscellaneous
export EDITOR=vim
export GEMEDITOR=subl
export CLICOLOR=1

# SVN
svndiff() { svn diff $@ | colordiff | less -R; }
alias svnadd="svn status | grep ^? | sed 's/^.* /svn add /' | bash"
alias svnrevert="svn revert -R ."
alias svnclean='for i in $(svn st | grep \? | cut -c 9-); do echo $i && rm -r $i; done'

# File and directory listings
alias ls="ls -F"
alias l="ls -lAh"
alias ll="ls -l"
alias la="ls -A"

# Changing directories
s() { cd ~/Sites/$1; }
c() { cd ~/Code/$1; }

# Completions
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
  source /usr/local/etc/bash_completion.d/git-completion.bash
fi

_c_complete() {
  local cur matches
  cur="${COMP_WORDS[COMP_CWORD]}"
  matches=$(basename ~/Code/*)
  COMPREPLY=( $(compgen -W "${matches}" -- ${cur}) )
}

_s_complete() {
  local cur matches
  cur="${COMP_WORDS[COMP_CWORD]}"
  matches=$(basename ~/Sites/*)
  COMPREPLY=( $(compgen -W "${matches}" -- ${cur}) )
}

complete -o default -F _c_complete c
complete -o default -F _s_complete s

# Ruby
alias be="bundle exec"
railsapp() {
  local template=~/Code/railsapp/template.rb
  [ -e $template ] && rails new $1 --skip-bundle -m $template
}

# rbenv
export PATH="/Users/jimmy/.rbenv/shims:${PATH}"
source "/usr/local/Cellar/rbenv/0.3.0/libexec/../completions/rbenv.bash"
rbenv rehash 2>/dev/null
rbenv() {
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  shell)
    eval `rbenv "sh-$command" "$@"`;;
  *)
    command rbenv "$command" "$@";;
  esac
}

# Node
ne() { PATH=`npm bin`:$PATH $1; }

# C
alias marvin="gcc -Wall -Wextra -ansi -pedantic"

# Local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi
