#!/usr/bin/env ruby
require "pp"

class Completion
  def initialize(command)
    @command = command
    @collection = @command == "s " ? sites : code_projects
  end

  def matches
    @collection.select do |task|
      task[0, typed.length] == typed
    end
  end

  private

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def sites
    `ls ~/Sites/`.split
  end

  def code_projects
    `ls ~/Code/`.split
  end
end

puts Completion.new(ENV["COMP_LINE"]).matches
exit 0
