#!/usr/bin/env bash

# Shell options
shopt -s globstar 2>/dev/null # requires Bash 4

# Colors
e=`printf "\033"`
end="$e[0m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
blue="$e[1;34m"
magenta="$e[1;35m"
darkcyan="$e[1;36m"

# Paths
export PATH="./.bundle/bin:/Users/jimmy/.rbenv/shims:/usr/local/share/python:/usr/local/bin:$PATH"
export NODE_PATH="/usr/local/lib/node_modules"

# Miscellaneous
export EDITOR=vim
export GEMEDITOR=subl
export CLICOLOR=1

# rbenv
source "/usr/local/Cellar/rbenv/0.3.0/libexec/../completions/rbenv.bash"
rbenv rehash 2>/dev/null
rbenv() {
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  shell)
    eval `rbenv "sh-$command" "$@"`;;
  *)
    command rbenv "$command" "$@";;
  esac
}

# Git
alias git=hub
_parse_git_branch() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}") "
}

# Hitch
hitch() {
  command hitch "$@"

  if [[ -s "$HOME/.hitch_export_authors" ]]; then
    source "$HOME/.hitch_export_authors"
  fi
}

alias unhitch='hitch -u'

hitch 1>/dev/null

_parse_hitch_pair() {
  in_repo=$(git symbolic-ref HEAD 2> /dev/null) || return
  [ -n "$GIT_AUTHOR_NAME" ] && echo "<${GIT_AUTHOR_NAME/ and //}> "
}

# SVN
svndiff() { svn diff $@ | colordiff | less -R; }
alias svnadd="svn status | grep ^? | sed 's/^.* /svn add /' | bash"
alias svnrevert="svn revert -R ."
alias svnclean='for i in $(svn st | grep \? | cut -c 9-); do echo $i && rm -r $i; done'

# File and directory listings
alias ls="ls -F"
alias l="ls -lAh"
alias ll="ls -l"
alias la="ls -A"

# Changing directories
c() { cd ~/Code/$1; }

# Completions
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
  source /usr/local/etc/bash_completion.d/git-completion.bash
fi

if [ -f /usr/local/etc/bash_completion.d/hub.bash_completion.sh ]; then
  source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
fi

_c_complete() {
  local cur matches
  cur="${COMP_WORDS[COMP_CWORD]}"
  matches=$(basename ~/Code/*)
  COMPREPLY=( $(compgen -W "${matches}" -- ${cur}) )
}

complete -o default -F _c_complete c

# Ruby
export RUBY_HEAP_MIN_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=300000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=79000000

alias be="bundle exec"

railsapp() {
  local template=~/Code/railsapp/template.rb
  [ -e $template ] && rails new $1 --skip-bundle -T -m $template
}

# Node
ne() { PATH=`npm bin`:$PATH $1; }

# C
alias marvin="gcc -Wall -Wextra -ansi -pedantic"

# Local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

# Prompt
export PS1="\[${red}\][\$(rbenv version-name)] \[${green}\]\w\[${darkcyan}\] \$(_parse_hitch_pair)\$(_parse_git_branch)\[${green}\]\\$\[${end}\] "
