#!/usr/bin/env bash

# Shell options
shopt -s globstar 2>/dev/null # requires Bash 4

# Colors
e=`printf "\033"`
end="$e[0m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
blue="$e[1;34m"
magenta="$e[1;35m"
darkcyan="$e[1;36m"

# Miscellaneous
export EDITOR=vim
export GEMEDITOR=vim
export CLICOLOR=1
export HISTCONTROL="ignoreboth"

# Paths
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# Git
if which hub > /dev/null; then
  alias git=hub
fi
_parse_git_branch() {
  ref=$(command git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}") "
}

# SVN
svndiff() { svn diff $@ | colordiff | less -R; }
alias svnadd="svn status | grep ^? | sed 's/^.* /svn add /' | bash"
alias svnrevert="svn revert -R ."
alias svnclean='for i in $(svn st | grep \? | cut -c 9-); do echo $i && rm -r $i; done'

# File and directory listings
alias ls="ls -F"
alias l="ls -lAh"
alias ll="ls -l"
alias la="ls -A"

# Completions
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
  source /usr/local/etc/bash_completion.d/git-completion.bash
fi

if [ -f /usr/local/etc/bash_completion.d/hub.bash_completion.sh ]; then
  source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
fi

alias be="bundle exec"

# Local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

# Prompt
export PS1="\[\033]0;\007\]\[${blue}\][\$(hostname -s)] \[${red}\][\$(rbenv version-name)] \[${green}\]\w\[${darkcyan}\] \$(_parse_git_branch)\[${green}\]\\$\[${end}\] "
