" Compatibility mode
set nocompatible

" BEGIN VUNDLE
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'skalnik/vim-vroom'
Bundle 'jgdavey/vim-railscasts'
Bundle 'kchmck/vim-coffee-script'
Bundle 'elzr/vim-json'
Bundle 'tpope/vim-surround'
Bundle 'jnwhiteh/vim-golang'
Bundle 'tpope/vim-markdown'
filetype plugin indent on
" END VUNDLE

" Syntax highlighting
syntax on

" Leader
let mapleader=","

" Tab stops
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Line numbers
set number
set ruler
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Colors
colorscheme railscasts

" Info display
set showcmd
set showmode

" Status line
set laststatus=2
set statusline=%-10.3n\
set statusline+=%f\
set statusline+=%h%m%r%w
set statusline+=\[%{strlen(&ft)?&ft:'none'}]
set statusline+=%=
set statusline+=%-14(%l,%c%V%)
set statusline+=%<%P

" Buffers
set hidden

" Command line completion
set wildmenu
set wildmode=list:longest

" Searching
set ignorecase
set smartcase
set incsearch
set hlsearch

" Visual bell
set visualbell

" Vroom
let g:vroom_use_bundle_exec = 0

" Strip trailing whitespace on save
function! <SID>StripTrailingWhitespace()
  let _s=@/
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction

" Autocommands
autocmd BufWritePre * :call <SID>StripTrailingWhitespace()

" Mappings
nnoremap <leader><leader> <c-^>
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
